// <auto-generated />
using System;
using HallRental.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HallRental.DAL.Migrations
{
    [DbContext(typeof(HallRentalDbContext))]
    partial class HallRentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HallRental.DAL.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HallId", "StartUtc", "EndUtc");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HallRental.DAL.Entities.BookingService", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PriceAtBooking")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookingId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BookingServices");
                });

            modelBuilder.Entity("HallRental.DAL.Entities.Hall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseHourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Capacity");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b388f3e-0fe7-4d01-9b6b-f1c4465cb815"),
                            BaseHourlyRate = 2000m,
                            Capacity = 50,
                            CreatedAtUtc = new DateTime(2026, 9, 7, 16, 57, 31, 776, DateTimeKind.Utc).AddTicks(76),
                            IsDeleted = false,
                            Name = "Зал A"
                        },
                        new
                        {
                            Id = new Guid("38e195b3-177d-4294-bfc3-dfb4fe81c723"),
                            BaseHourlyRate = 3500m,
                            Capacity = 100,
                            CreatedAtUtc = new DateTime(2026, 9, 7, 16, 57, 31, 776, DateTimeKind.Utc).AddTicks(76),
                            IsDeleted = false,
                            Name = "Зал B"
                        },
                        new
                        {
                            Id = new Guid("1f9bb736-7681-41ac-9e65-d086dc30903b"),
                            BaseHourlyRate = 1500m,
                            Capacity = 30,
                            CreatedAtUtc = new DateTime(2026, 9, 7, 16, 57, 31, 776, DateTimeKind.Utc).AddTicks(76),
                            IsDeleted = false,
                            Name = "Зал C"
                        });
                });

            modelBuilder.Entity("HallRental.DAL.Entities.HallService", b =>
                {
                    b.Property<Guid>("HallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HallId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("HallServices");

                    b.HasData(
                        new
                        {
                            HallId = new Guid("6b388f3e-0fe7-4d01-9b6b-f1c4465cb815"),
                            ServiceId = new Guid("a7f24c91-3d68-4e52-bf17-82c9d5a41e73")
                        },
                        new
                        {
                            HallId = new Guid("6b388f3e-0fe7-4d01-9b6b-f1c4465cb815"),
                            ServiceId = new Guid("3e91b7d4-6a25-4f08-8c53-d129e7a46b81")
                        },
                        new
                        {
                            HallId = new Guid("6b388f3e-0fe7-4d01-9b6b-f1c4465cb815"),
                            ServiceId = new Guid("c5824f16-9d37-4b60-ae28-71f3c95d824a")
                        },
                        new
                        {
                            HallId = new Guid("38e195b3-177d-4294-bfc3-dfb4fe81c723"),
                            ServiceId = new Guid("a7f24c91-3d68-4e52-bf17-82c9d5a41e73")
                        },
                        new
                        {
                            HallId = new Guid("38e195b3-177d-4294-bfc3-dfb4fe81c723"),
                            ServiceId = new Guid("3e91b7d4-6a25-4f08-8c53-d129e7a46b81")
                        },
                        new
                        {
                            HallId = new Guid("38e195b3-177d-4294-bfc3-dfb4fe81c723"),
                            ServiceId = new Guid("c5824f16-9d37-4b60-ae28-71f3c95d824a")
                        },
                        new
                        {
                            HallId = new Guid("1f9bb736-7681-41ac-9e65-d086dc30903b"),
                            ServiceId = new Guid("a7f24c91-3d68-4e52-bf17-82c9d5a41e73")
                        },
                        new
                        {
                            HallId = new Guid("1f9bb736-7681-41ac-9e65-d086dc30903b"),
                            ServiceId = new Guid("3e91b7d4-6a25-4f08-8c53-d129e7a46b81")
                        },
                        new
                        {
                            HallId = new Guid("1f9bb736-7681-41ac-9e65-d086dc30903b"),
                            ServiceId = new Guid("c5824f16-9d37-4b60-ae28-71f3c95d824a")
                        });
                });

            modelBuilder.Entity("HallRental.DAL.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7f24c91-3d68-4e52-bf17-82c9d5a41e73"),
                            CreatedAtUtc = new DateTime(2026, 9, 7, 16, 57, 31, 776, DateTimeKind.Utc).AddTicks(76),
                            Name = "Проєктор",
                            Price = 500m
                        },
                        new
                        {
                            Id = new Guid("3e91b7d4-6a25-4f08-8c53-d129e7a46b81"),
                            CreatedAtUtc = new DateTime(2026, 9, 7, 16, 57, 31, 776, DateTimeKind.Utc).AddTicks(76),
                            Name = "Wi-Fi",
                            Price = 300m
                        },
                        new
                        {
                            Id = new Guid("c5824f16-9d37-4b60-ae28-71f3c95d824a"),
                            CreatedAtUtc = new DateTime(2026, 9, 7, 16, 57, 31, 776, DateTimeKind.Utc).AddTicks(76),
                            Name = "Звук",
                            Price = 700m
                        });
                });

            modelBuilder.Entity("HallRental.DAL.Entities.Booking", b =>
                {
                    b.HasOne("HallRental.DAL.Entities.Hall", "Hall")
                        .WithMany("Bookings")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("HallRental.DAL.Entities.BookingService", b =>
                {
                    b.HasOne("HallRental.DAL.Entities.Booking", "Booking")
                        .WithMany("BookingServices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HallRental.DAL.Entities.Service", "Service")
                        .WithMany("BookingServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HallRental.DAL.Entities.HallService", b =>
                {
                    b.HasOne("HallRental.DAL.Entities.Hall", "Hall")
                        .WithMany("HallServices")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HallRental.DAL.Entities.Service", "Service")
                        .WithMany("HallServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HallRental.DAL.Entities.Booking", b =>
                {
                    b.Navigation("BookingServices");
                });

            modelBuilder.Entity("HallRental.DAL.Entities.Hall", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("HallServices");
                });

            modelBuilder.Entity("HallRental.DAL.Entities.Service", b =>
                {
                    b.Navigation("BookingServices");

                    b.Navigation("HallServices");
                });
#pragma warning restore 612, 618
        }
    }
}
